CREATE TABLE [dbo].[Exercises]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(100) NOT NULL,
	[Force] NVARCHAR(50) NOT NULL,
	[Level] NVARCHAR(50) NOT NULL,
	[Mechanic] NVARCHAR(30) NOT NULL,
	[Equipment] NVARCHAR(70) NOT NULL,
	[PrimaryMuscles] NVARCHAR(150) NOT NULL,
	[SecondaryMuscles] NVARCHAR(300) NOT NULL,
	[Instructions] NVARCHAR(MAX) NOT NULL,
	[Category] NVARCHAR(50) NOT NULL,
	[ImgPath1] NVARCHAR(200) NOT NULL,
	[ImgPath2] NVARCHAR(200) NOT NULL
)
