CREATE TABLE [dbo].[TrainingPlanExercises]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[TPId] INT NOT NULL,
	[EId] INT NOT NULL,
	[Series] INT NOT NULL,
	[Reps] NVARCHAR(50) NOT NULL,
	[Weights] NVARCHAR(200) NOT NULL,
	[Sequence] INT,
    CONSTRAINT [FK_TPId] FOREIGN KEY ([TPId]) REFERENCES [TrainingPlans]([Id]),
    CONSTRAINT [FK_EId] FOREIGN KEY ([EId]) REFERENCES [Exercises]([Id]),

)
