CREATE TABLE [dbo].[LocalUsers]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[UserName] NVARCHAR(256) NOT NULL,
	[Name] NVARCHAR(256) NOT NULL,
	[Password] NVARCHAR(500) NOT NULL,
	[Role] NVARCHAR(40) NOT NULL
)
