CREATE PROCEDURE [dbo].[spTrainingPlan_Delete]
	@Id INT
AS
BEGIN

	BEGIN TRANSACTION;

	BEGIN TRY
			DELETE FROM TrainingPlanExercises WHERE TPId = @Id;
			DELETE FROM TrainingPlans WHERE Id = @Id;
		COMMIT TRANSACTION;
	END TRY

	BEGIN CATCH
		ROLLBACK TRANSACTION;
	END CATCH

END
